version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  apt_packages:
    - cmake
    - doxygen
  jobs:
    pre_build:
      - cmake -B build -Dndtbl_BUILD_DOCS=ON -Dndtbl_BUILD_TESTING=OFF -Dndtbl_BUILD_BENCHMARKS=OFF
      - cmake --build build --target ndtbl-doxygen
    build:
      html:
        - uv run --project python/ndtbl sphinx-build -T -j auto -b html -d doc/_build/doctrees -D language=en doc $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: uv
      command: sync
      path: python/ndtbl
      extras:
        - docs

sphinx:
  configuration: doc/conf.py
