codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      cpp:
        target: 90
        flags:
          - cpp
      python:
        target: 90
        flags:
          - python

flags:
  cpp:
    paths:
      - include/
    carryforward: true
  python:
    paths:
      - python/ndtbl/src/ndtbl/
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "condensed_header,flags,condensed_files,condensed_footer"
  behavior: default
  require_changes: false

ignore:
  - "app/**"
  - "doc/**"
  - "tests/**"
  - "python/ndtbl/doc/**"
  - "python/ndtbl/tests/**"
